### ISSUE TITLE
Define location

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#1]
We're looking into https://opengrounds.virginia.edu .

**Comment by alizaidia** [comment]
OpenGrounds - pictures: https://www.flickr.com/photos/152458008@N02/with/37782284312/

**Comment by Daniel-Mietchen** [comment]
Thanks - very useful. Now let's see whether that works out.

**Comment by jcruser** [comment]
I have requested the space at Open Grounds from  8:00 am to 7:00 pm Saturday and from 8:30 am to 7:00 pm Sunday.  The contact at OG should approve the reservation soon.  When she does we can ask about how many people the space can hold.

**Comment by jcruser** [comment]
We've reserved Open Ground from 8:00 - 5:00 Saturday and 8:30 to 5:00 on Sunday. I am meeting with Ashley tomorrow to discuss the layout/logistics/technology.

**Comment by jcruser** [comment]
Met with Ashley. We have both rooms A &B for Saturday but only one for Sunday. The legal occupancy is 49 though Ashley recommended for what we're doing to stay between 30-40. 

There are tons of electrical outlets but wifi for people without UVA affiliation might be an issue - we'll need to arrange for guess passes. 

There are also a total of 4 screens that each have a mac mini so we can project/share on those however we want. Many of the walls are white boards as well. 

There is a small kitchen area for tea/coffee. Anything else we need we will have to bring in, they just ask that we clean up.

**Comment by alizaidia** [comment]
Awesome work! :)

**Comment by Daniel-Mietchen** [comment]
Sounds good, thanks. 
For guest access, we have #21.
For food, I just opened #22.
In terms of number of participants, there is #6.

Seems we're sorted out with this one - closing.
