### ISSUE TITLE
Think about how to link up the event with other open data activities at Charlottesville and beyond

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#11]
e.g. https://www.meetup.com/CharlottesvilleDataScience/
or http://www.opencon2017.org/satellite

**Comment by Daniel-Mietchen** [comment]
as well as https://github.com/sparcopen/doathon-dev / http://doathon.opencon2017.org/ on November 13.

**Comment by alizaidia** [comment]
CVille Open Data Portal: http://www.charlottesville.org/departments-and-services/departments-a-g/open-data
https://www.smartcville.com
Virginia data initiative: https://data.virginia.gov
Center for Open Science in Charlottesville: https://cos.io

**Comment by Daniel-Mietchen** [comment]
Closing for now as well, but may be worth revisiting for the next one(s).
