### ISSUE TITLE
Make plan for how to organize the lightning talks

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#12]
Some examples from London:
* [Here is a remote project pitch](http://www.youtube.com/watch?v=UMR7N193uM8) for [issue 36: R interface to anthropology database D-Place](https://github.com/sparcopen/open-research-doathon/issues/36).
* [Here is an in-the-room pitch](https://twitter.com/OKFN/status/838011416598700033) for [issue 35:  Newbies guide to Wikidata](https://github.com/sparcopen/open-research-doathon/issues/35).

**Comment by alizaidia** [comment]
-Everyone gets 1-3 minutes depending on how many attendees are present (idea pitches and lightning talks)
-Some Q&A if time is available

**Comment by Daniel-Mietchen** [comment]
Plan is as above. Closing.
