### ISSUE TITLE
Check past hackathons and similar events in or around C'ville

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#16]
try to find some public records of such events that have been organized in C'ville over the past 2 years, and see what we could learn from them.

**Comment by jcruser** [comment]
A few recent hackathons : 
**Hack UVA**: http://hackuva.io/ - goal to create a platform/application from scratch
**Charlottesville civic innovation day**: https://www.smartcville.com/charlottesville-civic-innovation-day-2017/ - thinking of how to solve c-ville specific problems with technology.
**Hoos Hacking** : https://www.eventbrite.com/e/hoos-hacking-registration-18999340539# - Social Enterprise Project Challenge to benefit Computers4Kids

**Comment by jcruser** [comment]
There is also a hackathon this weekend (3rd Annual Health UnBound Hack-a-Thon.) The theme will be focused on Virtual Reality and its applications in the medical field.  Representatives from the UVA Pediatric Department, McGuire VA Medical Center Assistive Technology Program, Willow Tree, and UVA VR labs will be the mentors/judges

**Comment by Daniel-Mietchen** [comment]
Here's a link to the Health UnBound Hack-a-Thon on Nov 4-5: https://career.virginia.edu/blog/2017/sep/healthunbounds-hubs-virtual-reality-hack-thon .

There's also the Data Science Meetup on Nov 16: https://www.meetup.com/CharlottesvilleDataScience/events/244483558/ .

**Comment by Daniel-Mietchen** [comment]
Closing for now. May be worth revisiting for the next iteration.
