### ISSUE TITLE
Define hashtag

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#2]
Could simply be [#Doathon](https://twitter.com/hashtag/doathon?f=tweets&vertical=default&src=hash) but something more specific might be useful.

**Comment by alizaidia** [comment]
#UVA-DO or #UVADO - have 0 results on Twitter Hashtag Search

**Comment by Daniel-Mietchen** [comment]
dashes break the hashtag on Twitter

**Comment by Daniel-Mietchen** [comment]
Seems
https://twitter.com/hashtag/CvilleDo
and
https://twitter.com/hashtag/UVaDo
and
https://twitter.com/hashtag/DSIDo
are still available.

I'd go for the first.

**Comment by Daniel-Mietchen** [comment]
We've now gone for [#DSIDo](https://twitter.com/hashtag/DSIDo).
