### ISSUE TITLE
Provide WiFi access to on-site participants

### ISSUE THREAD

**Issue by alizaidia** [UVA-DSI/2017-doathon#21]
[//]: # "=======================
Instructions for posting issues:
(1) Review what is already there. Perhaps a comment to an existing issue would be more appropriate than opening a new one?  Issues can be a topic idea, a cry for help, a to-do, or a discussion / question about the event itself.
(2) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

**Comment by Daniel-Mietchen** [comment]
The procedure for guest access to the UVA WiFi is explained at http://its.virginia.edu/wireless/device-guest-configure.html .

**Comment by jcruser** [comment]
Someone has to sponsor/request the guest access. It looks like Ali and I would be able to do that the day of or the day before.

**Comment by Daniel-Mietchen** [comment]
Would be good to have this sorted out a few days in advance.

**Comment by alizaidia** [comment]
Guess wifi passes being printed for event November 15/16

**Comment by Daniel-Mietchen** [comment]
Done.
