### ISSUE TITLE
Set up a registration mechanism

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#24]
Given that the space is limited (see #6), we will need some mechanism for on-site people to register. This should also help with planning food (#22).

For planning purposes, it would be useful to have an indication as to how many remote attendees we are to expect, so perhaps that registration mechanism should be aware of the options of on-site and remote participation (possibly separately for the two days).

Could e.g. be a Google form or an EventBrite page or something similar.

**Comment by alizaidia** [comment]
https://www.eventbrite.com/e/dsi-do-a-thon-tickets-39704865321
http://dsi.virginia.edu/pages/dsi-do-thon
