### ISSUE TITLE
Provide a channel for participants to express the things learned

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#28]
Should be nearly effortless to share. Could just be a GitHub ticket &mdash; see [example](https://github.com/sparcopen/open-research-doathon/issues/45).

**Comment by alizaidia** [comment]
http://dsi.virginia.edu/pages/dsi-do-thon
https://www.eventbrite.com/e/uva-do-a-thon-tickets-39704865321
