### ISSUE TITLE
Let us know you're around

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#40]
Once you've entered the room or are joining remotely, let us know by posting a brief message in this ticket. For more detailed information about you, please use the [Gdoc](https://docs.google.com/document/d/13IJTpte7IdbCjkNMcVPy5KMP8eKiYAcSVXQzNbfwu_M/edit) that we are using for collaborative notes.

**Comment by kzkedzierska** [comment]
brief comment :)

**Comment by Domlenart** [comment]
Brief comment

**Comment by nbhaip** [comment]
brief comment

**Comment by stolarczyk** [comment]
brief comment

**Comment by jcruser** [comment]
brief comment

**Comment by eih2nn** [comment]
👍

**Comment by rrobeva** [comment]
I am here ;-)

**Comment by abhijithmandya17** [comment]
Hi!

**Comment by rohanbapat** [comment]
1

**Comment by alizaidia** [comment]
Hi everyone!

**Comment by andrewbovey** [comment]
Here!

**Comment by Daniel-Mietchen** [comment]
Others who were here include @archana-bahuguna and @StephenHolzman and @Jo-Pan.

**Comment by Daniel-Mietchen** [comment]
There were a few more people attending who did not sign up here. If you know them, please point them here. 

As the event is wrapping up, I'm closing the ticket.

**Comment by pyflask** [comment]
I'll look at https://openpsychologydata.metajnl.com and other open data on psychology or non profits. I'll also check out the pro publica - for non profit info.

**Comment by pyflask** [comment]
It was a fun event. Lots of conversation and connectedness, nice folks, checking out toilet data on wikidata.org on World Toilet Day! Thanks Daniel.
