### ISSUE TITLE
Reach out to relevant communities about the event

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#8]
Depends on having defined them first, as discussed in #7.

**Comment by jcruser** [comment]
DSI students have indicated they would participate for a one day event (about 20 people). Only about 5 would participate for two days.

**Comment by jcruser** [comment]
Talked to Reggie about getting the Data Science Meetup group and the open data portal board involved. He's will to send out emails but we need to provide an intro/blurb

**Comment by Daniel-Mietchen** [comment]
We've done a bit of outreach in multiple directions - e.g. I notified the Data Science Meetup both via the website and via an in-person announcement - and the registrations are within expectations. So we'll keep an eye on the topic, but I'll close this ticket for now.
