### ISSUE TITLE
Think about illustrations

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/2017-doathon#9]
Mainly for the README but possibly for other purposes as well, especially when thinking about outreach for the event, as per #8.

**Comment by alizaidia** [comment]
I think all the photos have some rights reserved licenses - 
https://www.flickr.com/photos/descrier/16323834751/
https://www.flickr.com/photos/notbrucelee/8016172703/
https://www.flickr.com/photos/notbrucelee/8016198226/
https://www.flickr.com/photos/opensourceway/5538036200/
https://www.flickr.com/photos/ter-burg/35066253751/
https://www.flickr.com/photos/planeta/12684126665/
https://www.flickr.com/photos/ter-burg/34387237533/
https://www.flickr.com/photos/opensourceway/4968547566/
https://www.flickr.com/photos/cyberhades/8315266195/
https://www.flickr.com/photos/kamiphuc/11396380473/
https://www.flickr.com/photos/79237959@N02/12210424505/
https://www.flickr.com/photos/jannekestaaks/14411397343/

**Comment by Daniel-Mietchen** [comment]
I prefer stuff that's in the Public Domain/ under CC0. Could live with CC BY, would like to avoid anything more restrictive.

From your list above, the following are CC BY:
https://www.flickr.com/photos/descrier/16323834751/
https://www.flickr.com/photos/ter-burg/34387237533/
https://www.flickr.com/photos/kamiphuc/11396380473/

From London, we also have [this list](https://github.com/sparcopen/open-research-doathon/issues/3#issuecomment-282528369) of CC0 images.

**Comment by Daniel-Mietchen** [comment]
In the end, we did not use any illustrations.
